# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end

target 'Date_New' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SQLite.swift', '~> 0.12.0'

  # Pods for Date_New

  target 'Date_NewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Date_NewUITests' do
    # Pods for testing
  end
  
  

end
